# Databricks notebook source
# MAGIC %md
# MAGIC # Use Case 4 · Setup — schema + volume (standalone)
# MAGIC
# MAGIC **The monthly blend, without the desktop ETL tool.** This use case is
# MAGIC fully self-contained — it does not depend on any other use case in the
# MAGIC accelerator. Everything it needs is generated by `01_generate_sources`.
# MAGIC
# MAGIC All assets are prefixed **`dsg_`** (designer) in the shared schema, with
# MAGIC source files in the **`dsg_landing`** volume. Idempotent; `reset=yes`
# MAGIC drops the `dsg_` tables for a clean re-run.
# MAGIC
# MAGIC > **About this demo.** All data is synthetic; no customer data is used.

# COMMAND ----------

dbutils.widgets.text("catalog_name", "lr_serverless_aws_us_catalog")
dbutils.widgets.text("schema_name", "actuarial_excel_demo")
dbutils.widgets.text("dsg_volume_name", "dsg_landing")
dbutils.widgets.dropdown("reset", "no", ["no", "yes"])

catalog = dbutils.widgets.get("catalog_name")
schema = dbutils.widgets.get("schema_name")
volume = dbutils.widgets.get("dsg_volume_name")
fqn = f"{catalog}.{schema}"
vol_path = f"/Volumes/{catalog}/{schema}/{volume}"

# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {fqn}")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {fqn}.{volume}")
spark.sql(f"""
    COMMENT ON VOLUME {fqn}.{volume} IS
    'Use Case 4 (Lakeflow Designer) source files: the claims extract used for '
    'the drag-a-file-onto-the-canvas step. Standalone — no dependency on other '
    'use cases. Synthetic data.'
""")
print(f"✓ volume {vol_path}")

try:
    spark.sql(f"GRANT READ VOLUME ON VOLUME {fqn}.{volume} TO `account users`")
    print("✓ volume grant applied")
except Exception as e:
    print(f"[skip] grants: {str(e)[:120]}")

# COMMAND ----------

if dbutils.widgets.get("reset") == "yes":
    for t in ["dsg_claims_src", "dsg_premium_src", "dsg_segment",
              "dsg_benchmark", "dsg_experience"]:
        spark.sql(f"DROP TABLE IF EXISTS {fqn}.{t}")
        print(f"✓ dropped {fqn}.{t}")
    print("Reset complete.")
else:
    print("No reset requested.")

# COMMAND ----------

print("Setup complete. Next: 01_generate_sources.py")
